version: "3.8"
services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailnord-tailscale-${INSTANCE_NAME}
    hostname: tailnord-tailscale
    command: [
      '/scripts/tailscale_up.sh'
    ]
    user: root
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "tailscale status --json | jq -e '.BackendState==\"Running\" and (.TailscaleIPs|length>0) and (.HealthWarnings|length==0)'" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
    dns:
      - 1.1.1.1
      - 8.8.8.8
    volumes:
      - "/dev/net/tun:/dev/net/tun"
      - "./tailscale/state:/var/lib/tailscale"
      - "./tailscale/scripts:/scripts"
    environment:
      - TS_ENABLE_HEALTH_CHECK=true
      - TS_LOCAL_ADDR_PORT=0.0.0.0:9002
      - TAILSCALE_UP_LOGIN_SERVER=${TAILSCALE_UP_LOGIN_SERVER}
      - IP_NORDVPN=${IP_NORDVPN}
      - INSTANCE_NAME=${INSTANCE_NAME}
    cap_add:
      - net_admin
      - sys_module
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.forwarding=1
      - net.ipv6.conf.all.forwarding=1
    networks:
      tailnord-net:
        ipv4_address: ${IP_TAILSCALE}

  nordvpn:
    build:
      context: nordvpn
    container_name: tailnord-nordvpn-${INSTANCE_NAME}
    hostname: tailnord-nordvpn
    healthcheck:
      test:
        - CMD
        - sh
        - -c
        - "nordvpn status | grep -q '^Status: Connected$'"
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    entrypoint: [
      '/scripts/nordvpn_up.sh'
    ]
    restart: always
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.forwarding=1
      - net.ipv6.conf.all.disable_ipv6=1
    environment:
      - NORDVPN_TOKEN=${NORDVPN_TOKEN}
      - NORDVPN_ENDPOINT=${NORDVPN_ENDPOINT}
      - NORDVPN_TECHNOLOGY=${NORDVPN_TECHNOLOGY}
      - NORDVPN_OPENVPN_PROTOCOL=${NORDVPN_OPENVPN_PROTOCOL}
      - IP_SUBNET=${IP_SUBNET}
    volumes:
      - "/dev/net/tun:/dev/net/tun"
      - "./nordvpn/scripts:/scripts"
    cap_add:
      - net_admin
      - sys_module
    networks:
      tailnord-net:
        ipv4_address: ${IP_NORDVPN}

networks:
  tailnord-net:
    enable_ipv6: false
    ipam:
      config:
        - subnet: ${IP_SUBNET}

